var a=1;

/*

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consequat, felis id porta facilisis, libero erat aliquam purus, eget venenatis nisl purus bibendum orci. Sed eget enim nibh. Curabitur convallis rhoncus orci et tempus. Vivamus non erat dolor. Nam ante justo, tincidunt id consectetur in, mollis vel odio. Donec quis leo nulla. In justo lacus, sodales quis porta eget, egestas sollicitudin sem. Maecenas lacinia bibendum ante, sed dignissim magna fringilla sed. Maecenas at elit tellus. Sed adipiscing eros in eros varius a rhoncus purus varius. Donec iaculis diam porta risus vestibulum hendrerit.

Phasellus eu eleifend purus. Cras lectus mi, semper non ultricies at, luctus eu urna. Nunc ultrices dolor ac sem consequat in viverra leo lobortis. Donec eu enim et urna accumsan dignissim sit amet vel massa. Mauris porta augue in nisl feugiat lobortis id eget nisl. Morbi congue luctus neque, nec dictum erat iaculis a. Nullam suscipit condimentum sapien, a rutrum leo vehicula non. Fusce porttitor sodales risus, vel sodales dui pulvinar nec. In ultrices euismod mauris auctor lacinia. Mauris rhoncus ligula at tortor fermentum accumsan. Aenean et neque eget orci viverra feugiat sed sit amet erat. Suspendisse sapien diam, venenatis vitae pretium iaculis, blandit vitae neque. Ut elementum, orci sed semper suscipit, purus eros pulvinar justo, at venenatis enim quam sed augue. Quisque tristique accumsan ligula, vitae commodo ante dignissim at.

Quisque porttitor consectetur massa at congue. Vivamus rutrum aliquet neque nec interdum. Ut vulputate, lorem vel viverra faucibus, odio ligula tempus leo, sit amet iaculis risus arcu quis urna. Maecenas non lorem varius sapien blandit blandit vel eget lorem. Suspendisse in lorem eros. Mauris sit amet ligula lorem. Phasellus velit nisl, mollis sollicitudin vestibulum vel, convallis et metus. Suspendisse dapibus tortor sit amet turpis commodo eget ornare magna faucibus. Nullam vitae erat vel ipsum adipiscing consectetur vitae vitae tortor. Vestibulum facilisis suscipit tellus, non sodales est suscipit a.

Proin porta eros mattis nisi suscipit gravida. Nullam faucibus malesuada mauris id mattis. Vestibulum nunc mi, euismod a sagittis sed, viverra a urna. Nunc eget faucibus risus. Ut non turpis in urna tristique lacinia id sit amet nunc. Suspendisse scelerisque sodales nisl, a ultrices erat consectetur vitae. Phasellus ornare, quam sed accumsan malesuada, velit nunc egestas urna, vitae commodo eros neque non lectus. Sed semper cursus ante, sit amet ullamcorper lorem feugiat molestie. Sed ut est dui. Fusce quis sapien quis augue consectetur porta quis eu turpis. Donec sed ipsum lacus, ut tempor enim. Aliquam est mi, consequat sit amet cursus sed, dapibus eget velit.

Donec pharetra consequat euismod. Sed accumsan risus quis purus posuere a feugiat odio porttitor. Nulla a sapien at enim vulputate adipiscing. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac purus sed tortor tristique interdum quis ultricies mauris. Donec mollis tellus quis ipsum pellentesque aliquam. In hac habitasse platea dictumst. Curabitur a mattis ligula. Nam vel tellus turpis, ac dictum nisi. Cras blandit consectetur erat, vitae adipiscing arcu elementum quis. Sed cursus nisl in nulla congue in tincidunt sapien placerat. Donec dapibus pellentesque dolor et aliquam. Nam velit leo, vulputate aliquam lobortis ut, tincidunt ac neque. Suspendisse at nibh sed sem ultrices vulputate vel in metus. Mauris enim augue, mattis non iaculis ut, condimentum sit amet mauris. Nullam accumsan, massa et tempus convallis, justo leo tempus metus, sollicitudin eleifend eros orci vitae justo.

Nam ultricies interdum urna. Proin eget nisl sed est laoreet laoreet ac vitae nibh. Curabitur et neque in augue tempus vestibulum eu quis ante. Donec sodales hendrerit mi, a facilisis nisl tempus in. Morbi id vestibulum felis. Cras iaculis ligula luctus nisi vestibulum eget pharetra lacus hendrerit. Phasellus sed nisl non urna venenatis pharetra. Fusce et suscipit orci. Aliquam quis nisl magna, nec ornare nunc. In hac habitasse platea dictumst. Fusce id risus sed mi congue viverra. Fusce porttitor feugiat dapibus. Suspendisse viverra urna facilisis sapien consequat ac semper ipsum ornare. Nullam rhoncus lorem sit amet eros ultricies euismod auctor sapien consequat.

Cras urna enim, fermentum vitae ultrices vitae, tristique vitae lorem. Nulla hendrerit mi eget massa auctor in rutrum sapien imperdiet. Etiam a orci dolor, eget posuere sem. Morbi eleifend tincidunt mi, ac sagittis turpis tincidunt ut. Sed feugiat suscipit lacus. Nullam porttitor mattis diam, id vestibulum tellus semper ut. Donec ipsum lectus, bibendum sed suscipit id, suscipit vel elit. Vestibulum in nibh arcu, sit amet mattis sem. Duis sed mollis quam. Morbi pretium ultricies tortor, quis scelerisque tellus cursus vel. Ut iaculis semper nulla sed tempor. Proin odio eros, ultrices ac dapibus eu, mollis non eros. Etiam a sagittis lorem. Mauris lobortis auctor mattis.

Sed vel tellus vitae leo posuere scelerisque. Sed sed dui id mauris semper malesuada. Nulla bibendum orci metus, id auctor nisl. Fusce nec nunc ut neque varius lacinia. Maecenas viverra dapibus euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam nec nulla eget justo ullamcorper laoreet. Donec ultricies purus sed augue elementum malesuada.

Morbi eu dapibus velit. Fusce lacinia augue vitae erat facilisis dignissim. Integer egestas magna ac arcu ultrices congue. Fusce tristique condimentum felis eu fermentum. Pellentesque non nunc nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer imperdiet rutrum arcu sed posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Nunc adipiscing viverra eros sit amet tempor. Praesent vestibulum facilisis arcu quis dignissim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis libero mi, feugiat nec tempor ut, aliquam sed nisl. Curabitur ultrices tempor tempus. Nullam sit amet tortor est. Suspendisse tempor posuere enim nec euismod. Etiam tristique nibh pulvinar lorem vestibulum adipiscing. Integer viverra, justo quis varius fringilla, sapien velit consectetur nunc, in porta orci sem eget felis. Mauris leo magna, elementum nec malesuada eu, ultricies eu diam. Duis aliquet aliquam risus, sit amet ornare purus iaculis vel. Curabitur odio nibh, sodales et ultricies non, elementum ac nulla.

Nulla libero lacus, pulvinar sed mollis quis, porttitor sed elit. Pellentesque non nisl vitae orci fringilla ultricies. Donec ultrices tincidunt posuere. Nam condimentum, nibh nec semper rhoncus, libero elit ultrices metus, non viverra nibh orci et leo. Pellentesque aliquet risus non nunc consequat sollicitudin. Aenean rutrum tincidunt hendrerit. Aliquam ac lectus sit amet leo rutrum mollis nec quis velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ac nibh ut arcu tempor imperdiet. Etiam ultricies arcu eget augue venenatis pretium.

Ut urna felis, feugiat ut eleifend a, adipiscing non ante. Sed venenatis porta lacus, vel sagittis neque fringilla sit amet. Sed ut odio eu ante gravida imperdiet sit amet a neque. Aenean pretium dui ut lacus auctor rutrum. Vestibulum et enim magna, eget dictum diam. Maecenas id ante magna. Ut ultricies, urna non sodales rutrum, leo mauris imperdiet erat, adipiscing mattis enim ipsum eget urna. Sed semper ullamcorper arcu vitae ultricies. Aenean congue tincidunt nisi, sed fermentum sapien rutrum quis. Aenean non nulla leo. Nulla congue lectus nec sapien cursus sed fermentum turpis blandit. In hac habitasse platea dictumst. Mauris auctor adipiscing nunc et sagittis.

Integer interdum dui ac leo ullamcorper congue ornare dui pellentesque. Donec non erat felis. Quisque in lectus et est ullamcorper vehicula at non urna. Morbi orci orci, scelerisque a luctus non, ornare nec urna. Sed fermentum vehicula nulla ornare feugiat. Vivamus rutrum ipsum at dolor rutrum facilisis. Aenean pharetra pretium elit, quis tempor nunc ultricies in. Praesent ut condimentum eros. Maecenas velit nibh, tincidunt non dapibus vitae, suscipit sed quam. Nam eleifend orci id dolor ultricies pharetra.

In eleifend ante eu velit consectetur ultrices. Cras sed mauris at leo tempor semper. Sed in diam sapien. Aenean vestibulum felis sed tellus faucibus et consectetur enim facilisis. Integer in dolor eget tellus aliquam tincidunt sed at nunc. Proin condimentum convallis egestas. Donec eu tincidunt nisi.

Suspendisse vel mattis felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In eget quam lectus, non dapibus nibh. Proin ornare, mauris at volutpat egestas, leo leo suscipit arcu, sit amet dignissim lacus nibh in nisl. Nunc blandit urna ac nulla pellentesque auctor. Duis lobortis ullamcorper est, eu facilisis velit elementum in. Proin lobortis urna sit amet neque euismod sit amet dapibus sem tincidunt. Morbi nisi turpis, consequat eu tincidunt sed, tincidunt sed ligula. Proin pharetra rutrum risus vel rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque sit amet ipsum dolor, sit amet dignissim ipsum. Sed vitae nisl ligula, sed pellentesque nunc.

Integer est leo, aliquet ac egestas et, cursus eu justo. Sed sagittis consectetur urna eget congue. Sed ullamcorper sollicitudin elit, vel vehicula turpis dictum sit amet. Curabitur vulputate, dolor nec volutpat suscipit, ipsum nisl elementum leo, ut placerat ipsum metus vitae est. Integer cursus, urna at mattis volutpat, nisl nunc mollis massa, consectetur ullamcorper nisi magna id neque. Curabitur vitae est leo, sit amet congue leo. Maecenas a velit ultricies ipsum ornare posuere et congue sem. Suspendisse potenti. Duis leo lectus, egestas a dictum a, dictum id elit. Donec non augue nec nibh sodales molestie vitae quis neque. Vivamus aliquam vehicula justo, tristique tincidunt purus auctor id. Donec venenatis arcu eget risus blandit et vestibulum turpis interdum. Etiam et eros lorem, vitae dapibus arcu. Integer sit amet convallis massa.

Nunc eget nisl mi. Morbi tempus imperdiet nisi sed faucibus. Vivamus porta nunc eu elit placerat commodo. Donec ullamcorper rutrum faucibus. Ut leo arcu, tristique vel fringilla in, viverra sed quam. Mauris vitae eros magna. Nullam sit amet dapibus lacus. Duis vel diam quam, at laoreet eros. Suspendisse ac ullamcorper turpis. Nunc mattis tincidunt dui, vitae commodo elit eleifend eget. Donec venenatis augue malesuada sem venenatis posuere. Quisque ut tellus libero. Nulla semper porta faucibus. Nulla elit turpis, tempor pellentesque ultrices vel, placerat sed libero. Ut sollicitudin lectus bibendum elit laoreet tincidunt.

Morbi at risus eu felis tincidunt pellentesque. Maecenas eros odio, viverra nec molestie volutpat, cursus in mauris. Aliquam erat volutpat. Aenean tincidunt sagittis ligula, quis luctus eros malesuada eu. Ut aliquam sollicitudin tristique. Donec porta sem sit amet sem tristique hendrerit. Morbi ultrices blandit urna a rhoncus. Nullam egestas dui pharetra purus varius suscipit. Vestibulum sed massa vel velit pellentesque lacinia sit amet et mauris. Vestibulum sed sapien erat. Sed dictum euismod tortor in rutrum. Morbi laoreet, felis vitae elementum ultrices, felis urna vehicula felis, at cursus purus arcu eget odio. Vivamus aliquet, tortor vitae ornare vestibulum, ligula tortor convallis leo, et rhoncus mauris sapien ut sapien. Quisque in urna eu dui facilisis lobortis. Pellentesque malesuada orci id quam pulvinar sodales in vitae lacus.

Fusce lobortis malesuada nunc nec semper. Nunc sit amet purus nibh, vitae faucibus mi. Aliquam ullamcorper egestas porttitor. Aenean diam augue, iaculis aliquam convallis eu, lobortis quis nisi. Nulla odio velit, sodales non convallis vel, aliquet sed tortor. Mauris et dictum neque. Donec sagittis varius felis sit amet vestibulum. Sed venenatis diam id odio pretium vel tristique libero hendrerit. Quisque at diam lectus, ac gravida mi.

Vestibulum elit massa, auctor sed iaculis consequat, sodales vitae enim. Donec sed eros eu risus faucibus sodales vel eget massa. Pellentesque gravida dui sed ipsum iaculis sagittis. Cras eleifend justo vel magna vulputate consequat dignissim dui porta. Ut quis nibh at nisi vehicula condimentum at at diam. In tincidunt dapibus libero, non dapibus turpis adipiscing quis. Pellentesque sit amet risus nec enim porttitor molestie. Pellentesque fringilla risus id dui fermentum pretium. Nam nec consectetur neque. Phasellus gravida diam quis risus cursus dignissim. Vivamus ultrices egestas dignissim. Quisque euismod egestas purus quis vehicula. Nam id egestas turpis. Vestibulum lorem nulla, semper vitae hendrerit rhoncus, malesuada congue leo. Curabitur vitae sollicitudin nunc. 


*/

